# Description:
# UseMetrics: The plugin does send information about your server to http://mcstats.org/plugin/Furniturelib
# Language: currently available Language:
#       - EN_en: english 
#       - DE_de: german
#       - PL_pl: polish | By gabixdev
#       - FR_fr: france | By Niasios
# useParticles: you can enable/disable the particles when it is not enough space
# DisableSitting: you can enable/disable the sit function of my plugin
# viewRange: This is the Chunk Range how long the player becomes the ArmorStands rendered you can make it smaller to reduce the CLIENT Lags.
# LimitType: This is the limitation type
#       - PLAYER: You can specify player kits and give your player the permissions furniture.limit.<kit>
#       - WORLD: You can specify the limit from models for each world
#       - CHUNK: You can specify the limit from models for every chunk
# ProtectionLib/RegionMemberAccess: You can enable/disable the access for region Owners to interact with another Models
# Database/type: This is the Database type
#       - SQLite: this saves the Furniture infos at plugins/Furniturelib/*.db
#       - MySQL: this saves the Furniture infos at a extern Database
# Database/database: this is the database name
# Database/user: this is the user to access the database
# Database/password: this is the password to access the database
# Database/port: this is the connection port for the Database
# Database/host: this is the ipadress or a domain to connect to a mysql database
# Database/importCheck: this import a *.db into a *.mysql database
# Purge: this is the option to autoPurge the Database and remove old Furnitures
# Purge/time: this it the time how long a player must be offline to remove it from the database
# Purge/autoPurge: this can be enable/disable to auto purge the models on Plugin loading
# Purge/removePurge: this option remove the models from the database without a reload from the plugin
# timer: this is the auto save timer
# timer/Enable: enable/disable this option to activate the timer
# timer/time: this it the save time
# autoFileUpdater: true/false it convert all files from <1.13 to 1.13 !
# PlaceMode: this is the mode of what the Furnitures are placed from each player
# Mode: "PRIVATE/PUBLIC" : set all new placed furnitures to private or public
# Access: "INTERACT/BREAK/BREAK_INTERACT" : it means the player have permissions to interact or break another Furnitures !
config:
  UseMetrics: true
  debugMode: false
  Language: "EN_en"
  useParticles: true
  DisableSitting: false
  ignoredWorlds: []
  viewRange: 10
  packetRenderMethode: false
  limit:
    limitConfig: "PLAYER"
    #You can give your player the permissions furniture.globallimit.# | furniture.globallimit.125 -> let the player can place 125 furnitures objects it override the limitconfig
    limitGlobal: 150
  glowing: true
  CheckUpdate: true
  rotateOnSit: true
  fileConverter:
    auto_mode: true
    database_table: FurnitureLib_Objects
  Creative:
    RemoveItems: false
    Interact: true
    Place: true
  PlaceMode:
    Mode: "PRIVATE"
    Access: "INTERACT"
  ProtectionLib:
    RegeionMemberAccess: false
  Database:
    type: "SQLite"
    database: "furniture"
    user: "ROOT"
    password: "123abcdefg"
    port: 3306
    host: "localhost"
    useSSL: false
    importCheck: false
    allowPublicKeyRetrieval: false
  Purge:
    time: 30
    autoPurge: false
    removePurge: false
  timer:
    Enable: false
    time: 300
  spamBlock:
    Place:
      Enable: true
      time: 5
    Break:
      Enable: true
      time: 5
    timeDisplay: "mm:ss:SSS"